---
name: test-wf
on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - v*
jobs:
  test-all:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./src/py/
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: "./src/py/pyproject.toml"

      - name: Install dependencies
        run: >
          uv sync
          --no-sources
          --all-extras
   #   - name: Install xvfb
   #     if: ${{ matrix.os == 'ubuntu-latest' }}
    #    run: sudo apt-get update && sudo apt-get install xvfb
    #    timeout-minutes: 1
        
      - name: Install google-chrome-for-testing
        run: uv run --no-sources kaleido_get_chrome -v

     # - name: Test mocker
     #   run: >
     #    uv run
     #     --no-sources kaleido_mocker
      #    --random 50
      #    --logistro-level INFO
      #    --n 1
       #   --timeout 200

      - name: Test
        if: ${{ ! runner.debug && matrix.os != 'ubuntu-latest' }}
        run: uv run --no-sources poe test
        timeout-minutes: 7

      - name: Test (Linux)
        if: ${{ ! runner.debug && matrix.os == 'ubuntu-latest' }}
        run: xvfb-run uv run --no-sources poe test
        timeout-minutes: 7

      - name: Test (Debug)
        if: runner.debug
        run: uv run --no-sources poe debug-test

      - name: Test (Debug, Linux)
        if: ${{ runner.debug && matrix.os == 'ubuntu-latest' }}
        run: xvfb-run uv run --no-sources poe debug-test
        timeout-minutes: 7
